<a href="https://colab.research.google.com/github/Guruvellitarun/Bulldozer_Price_Pediction/blob/main/Name_llm_tunning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install unsloth trl peft accelerate bitsandbytes

Collecting unsloth
  Downloading unsloth-2025.8.10-py3-none-any.whl.metadata (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.3/52.3 kB 4.8 MB/s eta 0:00:00
Collecting trl
  Downloading trl-0.21.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.17.1)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.10.1)
Collecting bitsandbytes
  Downloading bitsandbytes-0.47.0-py3-none-manylinux_2_24_x86_64.whl.metadata (11 kB)
Collecting unsloth_zoo>=2025.8.9 (from unsloth)
  Downloading unsloth_zoo-2025.8.9-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.8.0+cu126)
Collecting xformers>=0.0.27.post2 (from unsloth)
  Downloading xformers-0.0.32.post2-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (1.1 kB)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from unsloth) (25.0)
Collecting tyro (from unsloth)
  Downloading tyro-0.9.29-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: transformers!=4.47.0,!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,>=4.51.3 in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.55.4)
Collecting datasets<4.0.0,>=3.4.1 (from unsloth)
  Downloading datasets-3.6.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.2.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.9.5)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.45.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.0.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.29.5)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.34.4)
Requirement already satisfied: hf_transfer in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.1.9)
Requirement already satisfied: diffusers in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.35.1)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.23.0+cu126)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from peft) (6.0.2)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from peft) (0.6.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0,>=3.4.1->unsloth) (3.19.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0,>=3.4.1->unsloth) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0,>=3.4.1->unsloth) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0,>=3.4.1->unsloth) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0,>=3.4.1->unsloth) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0,>=3.4.1->unsloth) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0,>=3.4.1->unsloth) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.34.0->unsloth) (1.1.8)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->unsloth) (1.11.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.47.0,!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,>=4.51.3->unsloth) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.47.0,!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,>=4.51.3->unsloth) (0.21.4)
Requirement already satisfied: torchao in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2025.8.9->unsloth) (0.10.0)
Collecting cut_cross_entropy (from unsloth_zoo>=2025.8.9->unsloth)
  Downloading cut_cross_entropy-25.1.1-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo>=2025.8.9->unsloth) (11.3.0)
Collecting msgspec (from unsloth_zoo>=2025.8.9->unsloth)
  Downloading msgspec-0.19.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.9 kB)
Requirement already satisfied: importlib_metadata in /usr/local/lib/python3.12/dist-packages (from diffusers->unsloth) (8.7.0)
Requirement already satisfied: docstring-parser>=0.15 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (0.17.0)
Requirement already satisfied: rich>=11.1.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (13.9.4)
Collecting shtab>=1.5.6 (from tyro->unsloth)
  Downloading shtab-1.7.2-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro->unsloth) (4.4.4)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (3.12.15)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<4.0.0,>=3.4.1->unsloth) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<4.0.0,>=3.4.1->unsloth) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<4.0.0,>=3.4.1->unsloth) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<4.0.0,>=3.4.1->unsloth) (2025.8.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=11.1.0->tyro->unsloth) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=11.1.0->tyro->unsloth) (2.19.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.4.0->unsloth) (1.3.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata->diffusers->unsloth) (3.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.4.0->unsloth) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets<4.0.0,>=3.4.1->unsloth) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets<4.0.0,>=3.4.1->unsloth) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets<4.0.0,>=3.4.1->unsloth) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.4.1->unsloth) (1.20.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=11.1.0->tyro->unsloth) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets<4.0.0,>=3.4.1->unsloth) (1.17.0)
Downloading unsloth-2025.8.10-py3-none-any.whl (312 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 312.9/312.9 kB 13.2 MB/s eta 0:00:00
Downloading trl-0.21.0-py3-none-any.whl (511 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.9/511.9 kB 21.1 MB/s eta 0:00:00
Downloading bitsandbytes-0.47.0-py3-none-manylinux_2_24_x86_64.whl (61.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 MB 11.8 MB/s eta 0:00:00
Downloading datasets-3.6.0-py3-none-any.whl (491 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.5/491.5 kB 28.7 MB/s eta 0:00:00
Downloading unsloth_zoo-2025.8.9-py3-none-any.whl (196 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 kB 16.9 MB/s eta 0:00:00
Downloading xformers-0.0.32.post2-cp39-abi3-manylinux_2_28_x86_64.whl (117.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.2/117.2 MB 5.6 MB/s eta 0:00:00
Downloading tyro-0.9.29-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.0/130.0 kB 12.2 MB/s eta 0:00:00
Downloading shtab-1.7.2-py3-none-any.whl (14 kB)
Downloading cut_cross_entropy-25.1.1-py3-none-any.whl (22 kB)
Downloading msgspec-0.19.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (213 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.6/213.6 kB 18.5 MB/s eta 0:00:00
Installing collected packages: shtab, msgspec, tyro, xformers, datasets, cut_cross_entropy, bitsandbytes, trl, unsloth_zoo, unsloth
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
Successfully installed bitsandbytes-0.47.0 cut_cross_entropy-25.1.1 datasets-3.6.0 msgspec-0.19.0 shtab-1.7.2 trl-0.21.0 tyro-0.9.29 unsloth-2025.8.10 unsloth_zoo-2025.8.9 xformers-0.0.32.post2

In [ ]:
import pandas as pd
import json
import re

In [ ]:
# # importing the csv file
# data = pd.read_excel('drive/MyDrive/Training_dataset.xlsx')
# data.head()

In [ ]:
# data.drop(['Exchange:Ticker', 'Company Type', 'Company Status',
#            'Geographic Locations', 'Security Tickers']
#           , axis=1, inplace=True)

In [ ]:
# data.columns

In [ ]:
# data.head()

In [ ]:
# data.describe()

In [ ]:
# count = (data['Business Description'].str.strip() == '-').sum()
# print("Rows with only '-' :", count)

In [ ]:
# rows_with_only_dash = data[data['Business Description'].str.strip() == '-']
# print(rows_with_only_dash)

In [ ]:
# data = data[data['Business Description'].str.strip() != '-']

In [ ]:
# data.describe()

In [ ]:
# import re

# def clean_company_name(name):
#     name = re.sub(r"\s*\(.*?\)", "", name)

#     name = re.sub(r"\b(Inc\.?|Corporation|Corp\.?|Ltd\.?|LLC|PLC)\b", "", name, flags=re.IGNORECASE)

#     name = re.sub(r"[.,]+$", "", name)

#     name = re.sub(r"\s+", " ", name).strip()

#     return name

In [ ]:
# # Apply to Company Name column
# data['Company Name'] = data['Company Name'].apply(clean_company_name)

In [ ]:
# import re

# suffixes = ["Inc", "Inc.", "LLC", "LLC.", "Ltd", "Ltd.", "Corporation", "Corp", "Corp."]

# def clean_description(row):
#     desc = str(row["Business Description"]).strip()
#     company = str(row["Company Name"]).strip()

#     # Pattern: Company name + optional comma + optional suffix
#     pattern = rf"^{re.escape(company)}(?:,?\s+(?:{'|'.join(suffixes)}))?\s*"

#     # Remove from start
#     desc = re.sub(pattern, "", desc, flags=re.IGNORECASE).strip(",. ").strip()

#     return desc

# # Apply safely
# data.loc[:, "Business Description"] = data.apply(clean_description, axis=1)

In [ ]:
# data.head()

In [ ]:
# # Our data is ready now we are going to convert this data into Jsonl format

# subset = data.head(1000)

# records = [
#     {"input": row["Business Description"], "output": row["Company Name"]}
#     for _, row in subset.iterrows()
# ]

# with open("companies_1000.json", "w") as f:
#     json.dump(records, f, indent=4)

# print("✅ Saved first 1000 rows to companies_1000.json")

In [ ]:
#import new dataset which is india companys
df = pd.read_csv("drive/MyDrive/Indian_Companies.csv")

/tmp/ipython-input-2778738948.py:2: DtypeWarning: Columns (3,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("drive/MyDrive/Indian_Companies.csv")

In [ ]:
df.head()

,Unnamed: 0,name,rating,reviews,domain,location,years_old,employee_strength,tags,about
0,0,TCS,3.9,16.1k,Public,Mumbai + 156 more,52 years old,10000+ employees,"Consulting, IT/ITES, MNC, Fortune500","Tata Consultancy Services is an IT services, c..."
1,1,Accenture,4.0,14.1k,Private,Dublin + 87 more,31 years old,10000+ employees,"Consulting, IT/ITES, MNC",Accenture is a leading global professional ser...
2,2,ICICI Bank,4.1,12.7k,Public,Mumbai + 724 more,26 years old,10000+ employees,"Banking/Insurance/Accounting, Financial Servic...",ICICI Bank is India's largest private sector b...
3,3,Cognizant,3.9,12.1k,Private,Teaneck + 44 more,26 years old,10000+ employees,"IT/ITES, MNC",Cognizant (NASDAQ-100: CTSH) is one of the wor...
4,4,HDFC Bank,4.0,10.9k,Public,Mumbai + 692 more,26 years old,10000+ employees,"Banking/Insurance/Accounting, Financial Servic...",HDFC Bank is one of India’s leading private ba...

In [ ]:
df.isna().sum()

Unnamed: 0                0
name                      0
rating                56501
reviews                   0
domain               380701
location             136124
years_old            444812
employee_strength    405953
tags                 315674
about                436950
dtype: int64

In [ ]:
len(df)

452520

In [ ]:
452521 - 436950

15571

In [ ]:
df_cleaned = df.dropna(subset=['about'])

In [ ]:
df_cleaned.isna().sum()

Unnamed: 0              0
name                    0
rating                790
reviews                 0
domain               2808
location              236
years_old            8063
employee_strength    1949
tags                 1794
about                   0
dtype: int64

In [ ]:
df_cleaned.drop(['Unnamed: 0', 'rating', 'reviews', 'domain', 'location', 'years_old', 'employee_strength', 'tags'], axis = 1, inplace = True)

/tmp/ipython-input-1035853946.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned.drop(['Unnamed: 0', 'rating', 'reviews', 'domain', 'location', 'years_old', 'employee_strength', 'tags'], axis = 1, inplace = True)

In [ ]:
df_cleaned.head()

         name                                              about
0         TCS  Tata Consultancy Services is an IT services, c...
1   Accenture  Accenture is a leading global professional ser...
2  ICICI Bank  ICICI Bank is India's largest private sector b...
3   Cognizant  Cognizant (NASDAQ-100: CTSH) is one of the wor...
4   HDFC Bank  HDFC Bank is one of India’s leading private ba...

In [ ]:
SUFFIXES = r"(limited|ltd|inc|llc|plc|corp(?:oration)?|company|co|group)"

def build_aliases(name: str, text: str):
    aliases = set()
    nm = (name or "").strip()
    if not nm:
      return aliases

    aliases.add(nm)

    # variant without corporate suffixes (for alias building only)
    nm_no_suf = re.sub(rf"\b{SUFFIXES}\b\.?", "", nm, flags=re.IGNORECASE).strip()
    if nm_no_suf and nm_no_suf.lower() != nm.lower():
        aliases.add(nm_no_suf)

    # acronym from first letters (e.g., Tata Consultancy Services -> TCS)
    words = re.findall(r"[A-Za-z0-9]+", nm_no_suf or nm)
    if len(words) >= 2:
        ac = "".join(w[0] for w in words).upper()
        if len(ac) >= 2:
            aliases.add(ac)

    # pull uppercase abbreviations/tickers from parentheses in the original text
    for par in re.findall(r"\(([^)]{1,40})\)", text or ""):
        for tok in re.findall(r"[A-Z]{2,6}", par):
            aliases.add(tok)

    return sorted(aliases, key=len, reverse=True)  # longer first

def clean_description(row):
    text = str(row.get("about", "") or "")
    name = str(row.get("name", "") or "")

    # 1) Remove URLs early
    text = re.sub(r"http\S+|www\.\S+", " ", text, flags=re.IGNORECASE)

    # 2) Build aliases BEFORE dropping parentheses so we can capture (TCS), (NASDAQ: CTSH), etc.
    aliases = build_aliases(name, text)

    # 3) Drop parenthetical blobs like (TCS), (NASDAQ: CTSH)
    text = re.sub(r"\([^)]*\)", " ", text)

    # 4) Remove exchange/ticker phrases that may appear outside parentheses
    text = re.sub(r"\b(NASDAQ|NYSE|BSE|NSE)\b[:\s]*[A-Z0-9.\-]{1,8}", " ", text, flags=re.IGNORECASE)

    # 5) Remove company name & aliases anywhere (with optional possessive ’s/'s)
    if aliases:
        pattern = r"(?<!\w)(?:" + "|".join(map(re.escape, aliases)) + r")(?:'s|’s)?(?!\w)"
        text = re.sub(pattern, " ", text, flags=re.IGNORECASE)

    # 6) Whitespace/punctuation tidy
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"^\W+|\W+$", "", text)
    return text.strip()

In [ ]:
# Apply cleaning
df_cleaned["clean_about"] = df_cleaned.apply(clean_description, axis=1)

/tmp/ipython-input-699567284.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["clean_about"] = df_cleaned.apply(clean_description, axis=1)

In [ ]:
df_cleaned.head()

,name,about,clean_about
0,TCS,"Tata Consultancy Services is an IT services, c...","Tata Consultancy Services is an IT services, c..."
1,Accenture,Accenture is a leading global professional ser...,is a leading global professional services comp...
2,ICICI Bank,ICICI Bank is India's largest private sector b...,is India's largest private sector bank with to...
3,Cognizant,Cognizant (NASDAQ-100: CTSH) is one of the wor...,is one of the world’s leading professional ser...
4,HDFC Bank,HDFC Bank is one of India’s leading private ba...,is one of India’s leading private banks and wa...

In [ ]:
df_cleaned.drop('about', axis = 1, inplace=True)

/tmp/ipython-input-1194023482.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned.drop('about', axis = 1, inplace=True)

In [ ]:
df_cleaned.head()

         name                                        clean_about
0         TCS  Tata Consultancy Services is an IT services, c...
1   Accenture  is a leading global professional services comp...
2  ICICI Bank  is India's largest private sector bank with to...
3   Cognizant  is one of the world’s leading professional ser...
4   HDFC Bank  is one of India’s leading private banks and wa...

In [ ]:
subset = df_cleaned

# Convert to list of dicts
records = [
    {"input": row["clean_about"], "output": row["name"]}
    for _, row in subset.iterrows()
]

# Save to JSON
with open("companies_clean.json", "w") as f:
    json.dump(records, f, indent=4)

print("✅ Saved cleaned dataset to companies_clean.json")

✅ Saved cleaned dataset to companies_clean.json

In [ ]:
# lets start our tunning
file = json.load(open("companies_clean.json", "r"))
print(file[1])

{'input': 'is a leading global professional services company, providing a broad range of services and solutions in strategy, consulting, digital, technology and operations. Combining unmatched experience and specialized skills across more than 40 industries and all business functions – underpinned by the world’s largest delivery network – works at the intersection of business and technology to help clients improve their performance and create sustainable value for their stakeholders. With 449,000 people serving clients in more than 120 countries, drives innovation to improve the way the world works and lives. Visit us at', 'output': 'Accenture'}

In [ ]:
# Checking the GPU
import torch
print(f"CUDA available : {torch.cuda.is_available()}")
print(f"GPU = {torch.cuda.get_device_name(0) if torch.cuda.is_available() else None}")

CUDA available : True
GPU = Tesla T4

In [ ]:
from unsloth import FastLanguageModel
import torch

model_name = "unsloth/Phi-3-mini-4k-instruct-bnb-4bit"

max_seq_leght = 2048
dtype = None

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = model_name,
    max_seq_length = max_seq_leght,
    dtype = dtype,
    load_in_4bit = True,
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2025.8.10: Fast Mistral patching. Transformers: 4.55.4.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.8.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.4.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.32.post2. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/2.26G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/194 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/458 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
from datasets import Dataset

def format_prompt(example):
    return (
        f"### Input: Business Description: {example['input']}\n"
        f"### Output: {json.dumps({'company_name': example['output']})}<|endoftext|>"
    )

# Load your file
with open("companies_clean.json", "r") as f:
    file = json.load(f)


formatted_data = [format_prompt(item) for item in file]
dataset = Dataset.from_dict({"text": formatted_data})

print(dataset[0]["text"])  # show first prompt

### Input: Business Description: Tata Consultancy Services is an IT services, consulting and business solutions organisation that has been partnering with the world’s largest businesses in their transformation journeys for the last 50 years. A part of the Tata group, India's largest multinational business group, has over 436,000 of the world’s best-trained consultants in 46 countries. The company is listed on the the India. '​ proactive stance on climate change and award winning work with communities across the world have earned it a place in leading sustainability indices such as the Dow Jones Sustainability Index , MSCI Global Sustainability Index and the FTSE4Good Emerging Index
### Output: {"company_name": "TCS"}<|endoftext|>

In [ ]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = [
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    lora_alpha = 32,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
    use_rslora = False,
    loftq_config = None,
)

Unsloth 2025.8.10 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.

In [ ]:
from trl import SFTTrainer
from transformers import TrainingArguments


trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=2048,  # Lowered
    dataset_num_proc=2,
    args=TrainingArguments(
        per_device_train_batch_size=1,   # Lowered
        gradient_accumulation_steps=4,
        warmup_steps=10,
        num_train_epochs=3,
        learning_rate=2e-4,
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        logging_steps=25,
        optim="adamw_torch",             # Safer optimizer
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=3407,
        output_dir="outputs",
        save_strategy="epoch",
        save_total_limit=2,
        dataloader_pin_memory=False,
        report_to="none",
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/15570 [00:00<?, ? examples/s]

In [ ]:
# Train the model
trainer_stats = trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 15,570 | Num Epochs = 3 | Total steps = 11,679
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 4 x 1) = 4
 "-____-"     Trainable parameters = 29,884,416 of 3,850,963,968 (0.78% trained)

Unsloth: Will smartly offload gradients to save VRAM!

In [ ]:
from unsloth import FastLanguageModel
import torch

# Enable 2x faster inference
FastLanguageModel.for_inference(model)

while True:
    # User provides business description
    user_desc = input("Enter a company description (or 'quit' to stop): ")
    if user_desc.lower() == "quit":
        break

    # Build messages (chat template style)
    messages = [
        {"role": "user", "content": f"### Input: Business Description: {user_desc}\n### Output:"}
    ]

    # Tokenize
    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt",
    ).to("cuda")

    # Generate
    outputs = model.generate(
        input_ids=inputs,
        max_new_tokens=128,
        use_cache=True,
        temperature=0.7,
        do_sample=True,
        top_p=0.9,
    )

    # Decode
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Print only the assistant's part (after "### Output:")
    if "### Output:" in response:
        response = response.split("### Output:")[-1].strip()

    print(f"\nPredicted company name: {response}\n")